/*
 * Cogbox
 * Cogbox AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cogbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.cogbox.api.client.api;

import io.cogbox.api.client.ApiCallback;
import io.cogbox.api.client.ApiClient;
import io.cogbox.api.client.ApiException;
import io.cogbox.api.client.ApiResponse;
import io.cogbox.api.client.Configuration;
import io.cogbox.api.client.Pair;
import io.cogbox.api.client.ProgressRequestBody;
import io.cogbox.api.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.cogbox.api.client.model.StorageAccessDto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ObjectStorageApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ObjectStorageApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ObjectStorageApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getPushAccess
     * @param xCogboxOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Temporary storage access has been generated </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPushAccessCall(@javax.annotation.Nullable String xCogboxOrganizationID, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/object-storage/push-access";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xCogboxOrganizationID != null) {
            localVarHeaderParams.put("X-Cogbox-Organization-ID", localVarApiClient.parameterToString(xCogboxOrganizationID));
        }


        String[] localVarAuthNames = new String[] { "bearer", "oauth2" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getPushAccessValidateBeforeCall(@javax.annotation.Nullable String xCogboxOrganizationID, final ApiCallback _callback) throws ApiException {
        return getPushAccessCall(xCogboxOrganizationID, _callback);

    }

    /**
     * Get temporary storage access for pushing objects
     * 
     * @param xCogboxOrganizationID Use with JWT to specify the organization ID (optional)
     * @return StorageAccessDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Temporary storage access has been generated </td><td>  -  </td></tr>
     </table>
     */
    public StorageAccessDto getPushAccess(@javax.annotation.Nullable String xCogboxOrganizationID) throws ApiException {
        ApiResponse<StorageAccessDto> localVarResp = getPushAccessWithHttpInfo(xCogboxOrganizationID);
        return localVarResp.getData();
    }

    /**
     * Get temporary storage access for pushing objects
     * 
     * @param xCogboxOrganizationID Use with JWT to specify the organization ID (optional)
     * @return ApiResponse&lt;StorageAccessDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Temporary storage access has been generated </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<StorageAccessDto> getPushAccessWithHttpInfo(@javax.annotation.Nullable String xCogboxOrganizationID) throws ApiException {
        okhttp3.Call localVarCall = getPushAccessValidateBeforeCall(xCogboxOrganizationID, null);
        Type localVarReturnType = new TypeToken<StorageAccessDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get temporary storage access for pushing objects (asynchronously)
     * 
     * @param xCogboxOrganizationID Use with JWT to specify the organization ID (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Temporary storage access has been generated </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getPushAccessAsync(@javax.annotation.Nullable String xCogboxOrganizationID, final ApiCallback<StorageAccessDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = getPushAccessValidateBeforeCall(xCogboxOrganizationID, _callback);
        Type localVarReturnType = new TypeToken<StorageAccessDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
