# coding: utf-8

from __future__ import annotations

# flake8: noqa
"""
    Cogbox

    Cogbox AI platform API Docs

    The version of the OpenAPI document: 1.0
    Contact: support@cogbox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # import models into model package
    from cogbox_api_client.models.account_provider import AccountProvider
    from cogbox_api_client.models.admin_create_runner import AdminCreateRunner
    from cogbox_api_client.models.admin_get_webhook_status200_response import AdminGetWebhookStatus200Response
    from cogbox_api_client.models.announcement import Announcement
    from cogbox_api_client.models.api_key_list import ApiKeyList
    from cogbox_api_client.models.api_key_response import ApiKeyResponse
    from cogbox_api_client.models.audit_log import AuditLog
    from cogbox_api_client.models.build_info import BuildInfo
    from cogbox_api_client.models.cogbox_configuration import CogboxConfiguration
    from cogbox_api_client.models.command import Command
    from cogbox_api_client.models.completion_context import CompletionContext
    from cogbox_api_client.models.completion_item import CompletionItem
    from cogbox_api_client.models.completion_list import CompletionList
    from cogbox_api_client.models.compressed_screenshot_response import CompressedScreenshotResponse
    from cogbox_api_client.models.computer_use_start_response import ComputerUseStartResponse
    from cogbox_api_client.models.computer_use_status_response import ComputerUseStatusResponse
    from cogbox_api_client.models.computer_use_stop_response import ComputerUseStopResponse
    from cogbox_api_client.models.create_api_key import CreateApiKey
    from cogbox_api_client.models.create_build_info import CreateBuildInfo
    from cogbox_api_client.models.create_docker_registry import CreateDockerRegistry
    from cogbox_api_client.models.create_linked_account import CreateLinkedAccount
    from cogbox_api_client.models.create_organization import CreateOrganization
    from cogbox_api_client.models.create_organization_invitation import CreateOrganizationInvitation
    from cogbox_api_client.models.create_organization_quota import CreateOrganizationQuota
    from cogbox_api_client.models.create_organization_region_quota import CreateOrganizationRegionQuota
    from cogbox_api_client.models.create_organization_role import CreateOrganizationRole
    from cogbox_api_client.models.create_region import CreateRegion
    from cogbox_api_client.models.create_region_response import CreateRegionResponse
    from cogbox_api_client.models.create_runner import CreateRunner
    from cogbox_api_client.models.create_runner_response import CreateRunnerResponse
    from cogbox_api_client.models.create_sandbox import CreateSandbox
    from cogbox_api_client.models.create_sandbox_snapshot import CreateSandboxSnapshot
    from cogbox_api_client.models.create_session_request import CreateSessionRequest
    from cogbox_api_client.models.create_snapshot import CreateSnapshot
    from cogbox_api_client.models.create_user import CreateUser
    from cogbox_api_client.models.create_volume import CreateVolume
    from cogbox_api_client.models.display_info_response import DisplayInfoResponse
    from cogbox_api_client.models.docker_registry import DockerRegistry
    from cogbox_api_client.models.download_files import DownloadFiles
    from cogbox_api_client.models.execute_request import ExecuteRequest
    from cogbox_api_client.models.execute_response import ExecuteResponse
    from cogbox_api_client.models.file_info import FileInfo
    from cogbox_api_client.models.file_status import FileStatus
    from cogbox_api_client.models.fork_sandbox import ForkSandbox
    from cogbox_api_client.models.git_add_request import GitAddRequest
    from cogbox_api_client.models.git_branch_request import GitBranchRequest
    from cogbox_api_client.models.git_checkout_request import GitCheckoutRequest
    from cogbox_api_client.models.git_clone_request import GitCloneRequest
    from cogbox_api_client.models.git_commit_info import GitCommitInfo
    from cogbox_api_client.models.git_commit_request import GitCommitRequest
    from cogbox_api_client.models.git_commit_response import GitCommitResponse
    from cogbox_api_client.models.git_delete_branch_request import GitDeleteBranchRequest
    from cogbox_api_client.models.git_repo_request import GitRepoRequest
    from cogbox_api_client.models.git_status import GitStatus
    from cogbox_api_client.models.gpu_type import GpuType
    from cogbox_api_client.models.health_controller_check200_response import HealthControllerCheck200Response
    from cogbox_api_client.models.health_controller_check200_response_info_value import HealthControllerCheck200ResponseInfoValue
    from cogbox_api_client.models.health_controller_check503_response import HealthControllerCheck503Response
    from cogbox_api_client.models.job import Job
    from cogbox_api_client.models.job_status import JobStatus
    from cogbox_api_client.models.job_type import JobType
    from cogbox_api_client.models.keyboard_hotkey_request import KeyboardHotkeyRequest
    from cogbox_api_client.models.keyboard_press_request import KeyboardPressRequest
    from cogbox_api_client.models.keyboard_type_request import KeyboardTypeRequest
    from cogbox_api_client.models.list_branch_response import ListBranchResponse
    from cogbox_api_client.models.list_sandboxes_response import ListSandboxesResponse
    from cogbox_api_client.models.log_entry import LogEntry
    from cogbox_api_client.models.lsp_completion_params import LspCompletionParams
    from cogbox_api_client.models.lsp_document_request import LspDocumentRequest
    from cogbox_api_client.models.lsp_location import LspLocation
    from cogbox_api_client.models.lsp_server_request import LspServerRequest
    from cogbox_api_client.models.lsp_symbol import LspSymbol
    from cogbox_api_client.models.match import Match
    from cogbox_api_client.models.metric_data_point import MetricDataPoint
    from cogbox_api_client.models.metric_series import MetricSeries
    from cogbox_api_client.models.metrics_response import MetricsResponse
    from cogbox_api_client.models.mouse_click_request import MouseClickRequest
    from cogbox_api_client.models.mouse_click_response import MouseClickResponse
    from cogbox_api_client.models.mouse_drag_request import MouseDragRequest
    from cogbox_api_client.models.mouse_drag_response import MouseDragResponse
    from cogbox_api_client.models.mouse_move_request import MouseMoveRequest
    from cogbox_api_client.models.mouse_move_response import MouseMoveResponse
    from cogbox_api_client.models.mouse_position import MousePosition
    from cogbox_api_client.models.mouse_scroll_request import MouseScrollRequest
    from cogbox_api_client.models.mouse_scroll_response import MouseScrollResponse
    from cogbox_api_client.models.oidc_config import OidcConfig
    from cogbox_api_client.models.organization import Organization
    from cogbox_api_client.models.organization_invitation import OrganizationInvitation
    from cogbox_api_client.models.organization_role import OrganizationRole
    from cogbox_api_client.models.organization_sandbox_default_limited_network_egress import OrganizationSandboxDefaultLimitedNetworkEgress
    from cogbox_api_client.models.organization_suspension import OrganizationSuspension
    from cogbox_api_client.models.organization_usage_overview import OrganizationUsageOverview
    from cogbox_api_client.models.organization_user import OrganizationUser
    from cogbox_api_client.models.otel_config import OtelConfig
    from cogbox_api_client.models.paginated_audit_logs import PaginatedAuditLogs
    from cogbox_api_client.models.paginated_jobs import PaginatedJobs
    from cogbox_api_client.models.paginated_logs import PaginatedLogs
    from cogbox_api_client.models.paginated_sandboxes_deprecated import PaginatedSandboxesDeprecated
    from cogbox_api_client.models.paginated_snapshots import PaginatedSnapshots
    from cogbox_api_client.models.paginated_traces import PaginatedTraces
    from cogbox_api_client.models.poll_jobs_response import PollJobsResponse
    from cogbox_api_client.models.port_preview_url import PortPreviewUrl
    from cogbox_api_client.models.position import Position
    from cogbox_api_client.models.posthog_config import PosthogConfig
    from cogbox_api_client.models.process_errors_response import ProcessErrorsResponse
    from cogbox_api_client.models.process_logs_response import ProcessLogsResponse
    from cogbox_api_client.models.process_restart_response import ProcessRestartResponse
    from cogbox_api_client.models.process_status_response import ProcessStatusResponse
    from cogbox_api_client.models.project_dir_response import ProjectDirResponse
    from cogbox_api_client.models.pty_create_request import PtyCreateRequest
    from cogbox_api_client.models.pty_create_response import PtyCreateResponse
    from cogbox_api_client.models.pty_list_response import PtyListResponse
    from cogbox_api_client.models.pty_resize_request import PtyResizeRequest
    from cogbox_api_client.models.pty_session_info import PtySessionInfo
    from cogbox_api_client.models.range import Range
    from cogbox_api_client.models.rate_limit_config import RateLimitConfig
    from cogbox_api_client.models.rate_limit_entry import RateLimitEntry
    from cogbox_api_client.models.regenerate_api_key_response import RegenerateApiKeyResponse
    from cogbox_api_client.models.region import Region
    from cogbox_api_client.models.region_quota import RegionQuota
    from cogbox_api_client.models.region_screenshot_response import RegionScreenshotResponse
    from cogbox_api_client.models.region_type import RegionType
    from cogbox_api_client.models.region_usage_overview import RegionUsageOverview
    from cogbox_api_client.models.registry_push_access_dto import RegistryPushAccessDto
    from cogbox_api_client.models.replace_request import ReplaceRequest
    from cogbox_api_client.models.replace_result import ReplaceResult
    from cogbox_api_client.models.resize_sandbox import ResizeSandbox
    from cogbox_api_client.models.runner import Runner
    from cogbox_api_client.models.runner_class import RunnerClass
    from cogbox_api_client.models.runner_full import RunnerFull
    from cogbox_api_client.models.runner_health_metrics import RunnerHealthMetrics
    from cogbox_api_client.models.runner_healthcheck import RunnerHealthcheck
    from cogbox_api_client.models.runner_service_health import RunnerServiceHealth
    from cogbox_api_client.models.runner_snapshot_dto import RunnerSnapshotDto
    from cogbox_api_client.models.runner_state import RunnerState
    from cogbox_api_client.models.sandbox import Sandbox
    from cogbox_api_client.models.sandbox_class import SandboxClass
    from cogbox_api_client.models.sandbox_desired_state import SandboxDesiredState
    from cogbox_api_client.models.sandbox_labels import SandboxLabels
    from cogbox_api_client.models.sandbox_list_item import SandboxListItem
    from cogbox_api_client.models.sandbox_list_sort_direction import SandboxListSortDirection
    from cogbox_api_client.models.sandbox_list_sort_field import SandboxListSortField
    from cogbox_api_client.models.sandbox_state import SandboxState
    from cogbox_api_client.models.sandbox_volume import SandboxVolume
    from cogbox_api_client.models.screenshot_response import ScreenshotResponse
    from cogbox_api_client.models.search_files_response import SearchFilesResponse
    from cogbox_api_client.models.send_webhook_dto import SendWebhookDto
    from cogbox_api_client.models.session import Session
    from cogbox_api_client.models.session_execute_request import SessionExecuteRequest
    from cogbox_api_client.models.session_execute_response import SessionExecuteResponse
    from cogbox_api_client.models.set_snapshot_general_status_dto import SetSnapshotGeneralStatusDto
    from cogbox_api_client.models.signed_port_preview_url import SignedPortPreviewUrl
    from cogbox_api_client.models.snapshot_dto import SnapshotDto
    from cogbox_api_client.models.snapshot_manager_credentials import SnapshotManagerCredentials
    from cogbox_api_client.models.snapshot_state import SnapshotState
    from cogbox_api_client.models.ssh_access_dto import SshAccessDto
    from cogbox_api_client.models.ssh_access_validation_dto import SshAccessValidationDto
    from cogbox_api_client.models.storage_access_dto import StorageAccessDto
    from cogbox_api_client.models.toolbox_proxy_url import ToolboxProxyUrl
    from cogbox_api_client.models.trace_span import TraceSpan
    from cogbox_api_client.models.trace_summary import TraceSummary
    from cogbox_api_client.models.update_docker_registry import UpdateDockerRegistry
    from cogbox_api_client.models.update_job_status import UpdateJobStatus
    from cogbox_api_client.models.update_organization_default_region import UpdateOrganizationDefaultRegion
    from cogbox_api_client.models.update_organization_invitation import UpdateOrganizationInvitation
    from cogbox_api_client.models.update_organization_member_access import UpdateOrganizationMemberAccess
    from cogbox_api_client.models.update_organization_quota import UpdateOrganizationQuota
    from cogbox_api_client.models.update_organization_region_quota import UpdateOrganizationRegionQuota
    from cogbox_api_client.models.update_organization_role import UpdateOrganizationRole
    from cogbox_api_client.models.update_region import UpdateRegion
    from cogbox_api_client.models.update_sandbox_network_settings import UpdateSandboxNetworkSettings
    from cogbox_api_client.models.update_sandbox_state_dto import UpdateSandboxStateDto
    from cogbox_api_client.models.url import Url
    from cogbox_api_client.models.user import User
    from cogbox_api_client.models.user_home_dir_response import UserHomeDirResponse
    from cogbox_api_client.models.user_public_key import UserPublicKey
    from cogbox_api_client.models.volume_dto import VolumeDto
    from cogbox_api_client.models.volume_state import VolumeState
    from cogbox_api_client.models.webhook_app_portal_access import WebhookAppPortalAccess
    from cogbox_api_client.models.webhook_event import WebhookEvent
    from cogbox_api_client.models.webhook_initialization_status import WebhookInitializationStatus
    from cogbox_api_client.models.windows_response import WindowsResponse
    from cogbox_api_client.models.work_dir_response import WorkDirResponse

_DYNAMIC_IMPORTS: dict[str, str] = {
    "AccountProvider": "cogbox_api_client.models.account_provider",
    "AdminCreateRunner": "cogbox_api_client.models.admin_create_runner",
    "AdminGetWebhookStatus200Response": "cogbox_api_client.models.admin_get_webhook_status200_response",
    "Announcement": "cogbox_api_client.models.announcement",
    "ApiKeyList": "cogbox_api_client.models.api_key_list",
    "ApiKeyResponse": "cogbox_api_client.models.api_key_response",
    "AuditLog": "cogbox_api_client.models.audit_log",
    "BuildInfo": "cogbox_api_client.models.build_info",
    "CogboxConfiguration": "cogbox_api_client.models.cogbox_configuration",
    "Command": "cogbox_api_client.models.command",
    "CompletionContext": "cogbox_api_client.models.completion_context",
    "CompletionItem": "cogbox_api_client.models.completion_item",
    "CompletionList": "cogbox_api_client.models.completion_list",
    "CompressedScreenshotResponse": "cogbox_api_client.models.compressed_screenshot_response",
    "ComputerUseStartResponse": "cogbox_api_client.models.computer_use_start_response",
    "ComputerUseStatusResponse": "cogbox_api_client.models.computer_use_status_response",
    "ComputerUseStopResponse": "cogbox_api_client.models.computer_use_stop_response",
    "CreateApiKey": "cogbox_api_client.models.create_api_key",
    "CreateBuildInfo": "cogbox_api_client.models.create_build_info",
    "CreateDockerRegistry": "cogbox_api_client.models.create_docker_registry",
    "CreateLinkedAccount": "cogbox_api_client.models.create_linked_account",
    "CreateOrganization": "cogbox_api_client.models.create_organization",
    "CreateOrganizationInvitation": "cogbox_api_client.models.create_organization_invitation",
    "CreateOrganizationQuota": "cogbox_api_client.models.create_organization_quota",
    "CreateOrganizationRegionQuota": "cogbox_api_client.models.create_organization_region_quota",
    "CreateOrganizationRole": "cogbox_api_client.models.create_organization_role",
    "CreateRegion": "cogbox_api_client.models.create_region",
    "CreateRegionResponse": "cogbox_api_client.models.create_region_response",
    "CreateRunner": "cogbox_api_client.models.create_runner",
    "CreateRunnerResponse": "cogbox_api_client.models.create_runner_response",
    "CreateSandbox": "cogbox_api_client.models.create_sandbox",
    "CreateSandboxSnapshot": "cogbox_api_client.models.create_sandbox_snapshot",
    "CreateSessionRequest": "cogbox_api_client.models.create_session_request",
    "CreateSnapshot": "cogbox_api_client.models.create_snapshot",
    "CreateUser": "cogbox_api_client.models.create_user",
    "CreateVolume": "cogbox_api_client.models.create_volume",
    "DisplayInfoResponse": "cogbox_api_client.models.display_info_response",
    "DockerRegistry": "cogbox_api_client.models.docker_registry",
    "DownloadFiles": "cogbox_api_client.models.download_files",
    "ExecuteRequest": "cogbox_api_client.models.execute_request",
    "ExecuteResponse": "cogbox_api_client.models.execute_response",
    "FileInfo": "cogbox_api_client.models.file_info",
    "FileStatus": "cogbox_api_client.models.file_status",
    "ForkSandbox": "cogbox_api_client.models.fork_sandbox",
    "GitAddRequest": "cogbox_api_client.models.git_add_request",
    "GitBranchRequest": "cogbox_api_client.models.git_branch_request",
    "GitCheckoutRequest": "cogbox_api_client.models.git_checkout_request",
    "GitCloneRequest": "cogbox_api_client.models.git_clone_request",
    "GitCommitInfo": "cogbox_api_client.models.git_commit_info",
    "GitCommitRequest": "cogbox_api_client.models.git_commit_request",
    "GitCommitResponse": "cogbox_api_client.models.git_commit_response",
    "GitDeleteBranchRequest": "cogbox_api_client.models.git_delete_branch_request",
    "GitRepoRequest": "cogbox_api_client.models.git_repo_request",
    "GitStatus": "cogbox_api_client.models.git_status",
    "GpuType": "cogbox_api_client.models.gpu_type",
    "HealthControllerCheck200Response": "cogbox_api_client.models.health_controller_check200_response",
    "HealthControllerCheck200ResponseInfoValue": "cogbox_api_client.models.health_controller_check200_response_info_value",
    "HealthControllerCheck503Response": "cogbox_api_client.models.health_controller_check503_response",
    "Job": "cogbox_api_client.models.job",
    "JobStatus": "cogbox_api_client.models.job_status",
    "JobType": "cogbox_api_client.models.job_type",
    "KeyboardHotkeyRequest": "cogbox_api_client.models.keyboard_hotkey_request",
    "KeyboardPressRequest": "cogbox_api_client.models.keyboard_press_request",
    "KeyboardTypeRequest": "cogbox_api_client.models.keyboard_type_request",
    "ListBranchResponse": "cogbox_api_client.models.list_branch_response",
    "ListSandboxesResponse": "cogbox_api_client.models.list_sandboxes_response",
    "LogEntry": "cogbox_api_client.models.log_entry",
    "LspCompletionParams": "cogbox_api_client.models.lsp_completion_params",
    "LspDocumentRequest": "cogbox_api_client.models.lsp_document_request",
    "LspLocation": "cogbox_api_client.models.lsp_location",
    "LspServerRequest": "cogbox_api_client.models.lsp_server_request",
    "LspSymbol": "cogbox_api_client.models.lsp_symbol",
    "Match": "cogbox_api_client.models.match",
    "MetricDataPoint": "cogbox_api_client.models.metric_data_point",
    "MetricSeries": "cogbox_api_client.models.metric_series",
    "MetricsResponse": "cogbox_api_client.models.metrics_response",
    "MouseClickRequest": "cogbox_api_client.models.mouse_click_request",
    "MouseClickResponse": "cogbox_api_client.models.mouse_click_response",
    "MouseDragRequest": "cogbox_api_client.models.mouse_drag_request",
    "MouseDragResponse": "cogbox_api_client.models.mouse_drag_response",
    "MouseMoveRequest": "cogbox_api_client.models.mouse_move_request",
    "MouseMoveResponse": "cogbox_api_client.models.mouse_move_response",
    "MousePosition": "cogbox_api_client.models.mouse_position",
    "MouseScrollRequest": "cogbox_api_client.models.mouse_scroll_request",
    "MouseScrollResponse": "cogbox_api_client.models.mouse_scroll_response",
    "OidcConfig": "cogbox_api_client.models.oidc_config",
    "Organization": "cogbox_api_client.models.organization",
    "OrganizationInvitation": "cogbox_api_client.models.organization_invitation",
    "OrganizationRole": "cogbox_api_client.models.organization_role",
    "OrganizationSandboxDefaultLimitedNetworkEgress": "cogbox_api_client.models.organization_sandbox_default_limited_network_egress",
    "OrganizationSuspension": "cogbox_api_client.models.organization_suspension",
    "OrganizationUsageOverview": "cogbox_api_client.models.organization_usage_overview",
    "OrganizationUser": "cogbox_api_client.models.organization_user",
    "OtelConfig": "cogbox_api_client.models.otel_config",
    "PaginatedAuditLogs": "cogbox_api_client.models.paginated_audit_logs",
    "PaginatedJobs": "cogbox_api_client.models.paginated_jobs",
    "PaginatedLogs": "cogbox_api_client.models.paginated_logs",
    "PaginatedSandboxesDeprecated": "cogbox_api_client.models.paginated_sandboxes_deprecated",
    "PaginatedSnapshots": "cogbox_api_client.models.paginated_snapshots",
    "PaginatedTraces": "cogbox_api_client.models.paginated_traces",
    "PollJobsResponse": "cogbox_api_client.models.poll_jobs_response",
    "PortPreviewUrl": "cogbox_api_client.models.port_preview_url",
    "Position": "cogbox_api_client.models.position",
    "PosthogConfig": "cogbox_api_client.models.posthog_config",
    "ProcessErrorsResponse": "cogbox_api_client.models.process_errors_response",
    "ProcessLogsResponse": "cogbox_api_client.models.process_logs_response",
    "ProcessRestartResponse": "cogbox_api_client.models.process_restart_response",
    "ProcessStatusResponse": "cogbox_api_client.models.process_status_response",
    "ProjectDirResponse": "cogbox_api_client.models.project_dir_response",
    "PtyCreateRequest": "cogbox_api_client.models.pty_create_request",
    "PtyCreateResponse": "cogbox_api_client.models.pty_create_response",
    "PtyListResponse": "cogbox_api_client.models.pty_list_response",
    "PtyResizeRequest": "cogbox_api_client.models.pty_resize_request",
    "PtySessionInfo": "cogbox_api_client.models.pty_session_info",
    "Range": "cogbox_api_client.models.range",
    "RateLimitConfig": "cogbox_api_client.models.rate_limit_config",
    "RateLimitEntry": "cogbox_api_client.models.rate_limit_entry",
    "RegenerateApiKeyResponse": "cogbox_api_client.models.regenerate_api_key_response",
    "Region": "cogbox_api_client.models.region",
    "RegionQuota": "cogbox_api_client.models.region_quota",
    "RegionScreenshotResponse": "cogbox_api_client.models.region_screenshot_response",
    "RegionType": "cogbox_api_client.models.region_type",
    "RegionUsageOverview": "cogbox_api_client.models.region_usage_overview",
    "RegistryPushAccessDto": "cogbox_api_client.models.registry_push_access_dto",
    "ReplaceRequest": "cogbox_api_client.models.replace_request",
    "ReplaceResult": "cogbox_api_client.models.replace_result",
    "ResizeSandbox": "cogbox_api_client.models.resize_sandbox",
    "Runner": "cogbox_api_client.models.runner",
    "RunnerClass": "cogbox_api_client.models.runner_class",
    "RunnerFull": "cogbox_api_client.models.runner_full",
    "RunnerHealthMetrics": "cogbox_api_client.models.runner_health_metrics",
    "RunnerHealthcheck": "cogbox_api_client.models.runner_healthcheck",
    "RunnerServiceHealth": "cogbox_api_client.models.runner_service_health",
    "RunnerSnapshotDto": "cogbox_api_client.models.runner_snapshot_dto",
    "RunnerState": "cogbox_api_client.models.runner_state",
    "Sandbox": "cogbox_api_client.models.sandbox",
    "SandboxClass": "cogbox_api_client.models.sandbox_class",
    "SandboxDesiredState": "cogbox_api_client.models.sandbox_desired_state",
    "SandboxLabels": "cogbox_api_client.models.sandbox_labels",
    "SandboxListItem": "cogbox_api_client.models.sandbox_list_item",
    "SandboxListSortDirection": "cogbox_api_client.models.sandbox_list_sort_direction",
    "SandboxListSortField": "cogbox_api_client.models.sandbox_list_sort_field",
    "SandboxState": "cogbox_api_client.models.sandbox_state",
    "SandboxVolume": "cogbox_api_client.models.sandbox_volume",
    "ScreenshotResponse": "cogbox_api_client.models.screenshot_response",
    "SearchFilesResponse": "cogbox_api_client.models.search_files_response",
    "SendWebhookDto": "cogbox_api_client.models.send_webhook_dto",
    "Session": "cogbox_api_client.models.session",
    "SessionExecuteRequest": "cogbox_api_client.models.session_execute_request",
    "SessionExecuteResponse": "cogbox_api_client.models.session_execute_response",
    "SetSnapshotGeneralStatusDto": "cogbox_api_client.models.set_snapshot_general_status_dto",
    "SignedPortPreviewUrl": "cogbox_api_client.models.signed_port_preview_url",
    "SnapshotDto": "cogbox_api_client.models.snapshot_dto",
    "SnapshotManagerCredentials": "cogbox_api_client.models.snapshot_manager_credentials",
    "SnapshotState": "cogbox_api_client.models.snapshot_state",
    "SshAccessDto": "cogbox_api_client.models.ssh_access_dto",
    "SshAccessValidationDto": "cogbox_api_client.models.ssh_access_validation_dto",
    "StorageAccessDto": "cogbox_api_client.models.storage_access_dto",
    "ToolboxProxyUrl": "cogbox_api_client.models.toolbox_proxy_url",
    "TraceSpan": "cogbox_api_client.models.trace_span",
    "TraceSummary": "cogbox_api_client.models.trace_summary",
    "UpdateDockerRegistry": "cogbox_api_client.models.update_docker_registry",
    "UpdateJobStatus": "cogbox_api_client.models.update_job_status",
    "UpdateOrganizationDefaultRegion": "cogbox_api_client.models.update_organization_default_region",
    "UpdateOrganizationInvitation": "cogbox_api_client.models.update_organization_invitation",
    "UpdateOrganizationMemberAccess": "cogbox_api_client.models.update_organization_member_access",
    "UpdateOrganizationQuota": "cogbox_api_client.models.update_organization_quota",
    "UpdateOrganizationRegionQuota": "cogbox_api_client.models.update_organization_region_quota",
    "UpdateOrganizationRole": "cogbox_api_client.models.update_organization_role",
    "UpdateRegion": "cogbox_api_client.models.update_region",
    "UpdateSandboxNetworkSettings": "cogbox_api_client.models.update_sandbox_network_settings",
    "UpdateSandboxStateDto": "cogbox_api_client.models.update_sandbox_state_dto",
    "Url": "cogbox_api_client.models.url",
    "User": "cogbox_api_client.models.user",
    "UserHomeDirResponse": "cogbox_api_client.models.user_home_dir_response",
    "UserPublicKey": "cogbox_api_client.models.user_public_key",
    "VolumeDto": "cogbox_api_client.models.volume_dto",
    "VolumeState": "cogbox_api_client.models.volume_state",
    "WebhookAppPortalAccess": "cogbox_api_client.models.webhook_app_portal_access",
    "WebhookEvent": "cogbox_api_client.models.webhook_event",
    "WebhookInitializationStatus": "cogbox_api_client.models.webhook_initialization_status",
    "WindowsResponse": "cogbox_api_client.models.windows_response",
    "WorkDirResponse": "cogbox_api_client.models.work_dir_response",
}


def __getattr__(attr_name: str) -> object:
    module_path = _DYNAMIC_IMPORTS.get(attr_name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {attr_name!r}")
    mod = importlib.import_module(module_path)
    value = getattr(mod, attr_name)
    globals()[attr_name] = value
    return value


def __dir__() -> list[str]:
    return list(_DYNAMIC_IMPORTS.keys())
