/*
 * Cogbox
 * Cogbox AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cogbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.cogbox.api.client.api;

import io.cogbox.api.client.ApiException;
import io.cogbox.api.client.model.HealthControllerCheck200Response;
import io.cogbox.api.client.model.HealthControllerCheck503Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthApi
 */
@Disabled
public class HealthApiTest {

    private final HealthApi api = new HealthApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void healthControllerCheckTest() throws ApiException {
        HealthControllerCheck200Response response = api.healthControllerCheck();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void healthControllerLiveTest() throws ApiException {
        api.healthControllerLive();
        // TODO: test validations
    }

}
