/* tslint:disable */
/* eslint-disable */
/**
 * Cogbox Billing API
 * Cogbox Billing API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const InvoicePaymentStatus = {
    InvoicePaymentStatusPending: 'pending',
    InvoicePaymentStatusSucceeded: 'succeeded',
    InvoicePaymentStatusFailed: 'failed',
} as const;

export type InvoicePaymentStatus = typeof InvoicePaymentStatus[keyof typeof InvoicePaymentStatus];



