# coding: utf-8

from __future__ import annotations

# flake8: noqa
"""
    Cogbox Toolbox API

    Cogbox Toolbox API. The base URL comes from the sandbox's `toolboxProxyUrl` field (returned in sandbox DTO by the main Cogbox API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Cogbox Cloud: `https://proxy.cogbox.pazity.com/toolbox/{sandboxId}`.

    The version of the OpenAPI document: v0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import importlib
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # import models into model package
    from cogbox_toolbox_api_client_async.models.accessibility_bounds import AccessibilityBounds
    from cogbox_toolbox_api_client_async.models.accessibility_invoke_request import AccessibilityInvokeRequest
    from cogbox_toolbox_api_client_async.models.accessibility_node_request import AccessibilityNodeRequest
    from cogbox_toolbox_api_client_async.models.accessibility_nodes_response import AccessibilityNodesResponse
    from cogbox_toolbox_api_client_async.models.accessibility_set_value_request import AccessibilitySetValueRequest
    from cogbox_toolbox_api_client_async.models.accessibility_tree_response import AccessibilityTreeResponse
    from cogbox_toolbox_api_client_async.models.chart import Chart
    from cogbox_toolbox_api_client_async.models.chart_element import ChartElement
    from cogbox_toolbox_api_client_async.models.code_run_artifacts import CodeRunArtifacts
    from cogbox_toolbox_api_client_async.models.code_run_request import CodeRunRequest
    from cogbox_toolbox_api_client_async.models.code_run_response import CodeRunResponse
    from cogbox_toolbox_api_client_async.models.command import Command
    from cogbox_toolbox_api_client_async.models.completion_context import CompletionContext
    from cogbox_toolbox_api_client_async.models.completion_item import CompletionItem
    from cogbox_toolbox_api_client_async.models.completion_list import CompletionList
    from cogbox_toolbox_api_client_async.models.computer_use_accessibility_node import ComputerUseAccessibilityNode
    from cogbox_toolbox_api_client_async.models.computer_use_start_response import ComputerUseStartResponse
    from cogbox_toolbox_api_client_async.models.computer_use_status_response import ComputerUseStatusResponse
    from cogbox_toolbox_api_client_async.models.computer_use_stop_response import ComputerUseStopResponse
    from cogbox_toolbox_api_client_async.models.create_context_request import CreateContextRequest
    from cogbox_toolbox_api_client_async.models.create_session_request import CreateSessionRequest
    from cogbox_toolbox_api_client_async.models.display_info import DisplayInfo
    from cogbox_toolbox_api_client_async.models.display_info_response import DisplayInfoResponse
    from cogbox_toolbox_api_client_async.models.execute_request import ExecuteRequest
    from cogbox_toolbox_api_client_async.models.execute_response import ExecuteResponse
    from cogbox_toolbox_api_client_async.models.file_info import FileInfo
    from cogbox_toolbox_api_client_async.models.file_status import FileStatus
    from cogbox_toolbox_api_client_async.models.files_download_request import FilesDownloadRequest
    from cogbox_toolbox_api_client_async.models.find_accessibility_nodes_request import FindAccessibilityNodesRequest
    from cogbox_toolbox_api_client_async.models.git_add_request import GitAddRequest
    from cogbox_toolbox_api_client_async.models.git_branch_request import GitBranchRequest
    from cogbox_toolbox_api_client_async.models.git_checkout_request import GitCheckoutRequest
    from cogbox_toolbox_api_client_async.models.git_clone_request import GitCloneRequest
    from cogbox_toolbox_api_client_async.models.git_commit_info import GitCommitInfo
    from cogbox_toolbox_api_client_async.models.git_commit_request import GitCommitRequest
    from cogbox_toolbox_api_client_async.models.git_commit_response import GitCommitResponse
    from cogbox_toolbox_api_client_async.models.git_delete_branch_request import GitDeleteBranchRequest
    from cogbox_toolbox_api_client_async.models.git_repo_request import GitRepoRequest
    from cogbox_toolbox_api_client_async.models.git_status import GitStatus
    from cogbox_toolbox_api_client_async.models.initialize_request import InitializeRequest
    from cogbox_toolbox_api_client_async.models.interpreter_context import InterpreterContext
    from cogbox_toolbox_api_client_async.models.is_port_in_use_response import IsPortInUseResponse
    from cogbox_toolbox_api_client_async.models.keyboard_hotkey_request import KeyboardHotkeyRequest
    from cogbox_toolbox_api_client_async.models.keyboard_press_request import KeyboardPressRequest
    from cogbox_toolbox_api_client_async.models.keyboard_type_request import KeyboardTypeRequest
    from cogbox_toolbox_api_client_async.models.list_branch_response import ListBranchResponse
    from cogbox_toolbox_api_client_async.models.list_contexts_response import ListContextsResponse
    from cogbox_toolbox_api_client_async.models.list_recordings_response import ListRecordingsResponse
    from cogbox_toolbox_api_client_async.models.lsp_completion_params import LspCompletionParams
    from cogbox_toolbox_api_client_async.models.lsp_document_request import LspDocumentRequest
    from cogbox_toolbox_api_client_async.models.lsp_location import LspLocation
    from cogbox_toolbox_api_client_async.models.lsp_position import LspPosition
    from cogbox_toolbox_api_client_async.models.lsp_range import LspRange
    from cogbox_toolbox_api_client_async.models.lsp_server_request import LspServerRequest
    from cogbox_toolbox_api_client_async.models.lsp_symbol import LspSymbol
    from cogbox_toolbox_api_client_async.models.match import Match
    from cogbox_toolbox_api_client_async.models.mouse_click_request import MouseClickRequest
    from cogbox_toolbox_api_client_async.models.mouse_click_response import MouseClickResponse
    from cogbox_toolbox_api_client_async.models.mouse_drag_request import MouseDragRequest
    from cogbox_toolbox_api_client_async.models.mouse_drag_response import MouseDragResponse
    from cogbox_toolbox_api_client_async.models.mouse_move_request import MouseMoveRequest
    from cogbox_toolbox_api_client_async.models.mouse_position_response import MousePositionResponse
    from cogbox_toolbox_api_client_async.models.mouse_scroll_request import MouseScrollRequest
    from cogbox_toolbox_api_client_async.models.port_list import PortList
    from cogbox_toolbox_api_client_async.models.position import Position
    from cogbox_toolbox_api_client_async.models.process_errors_response import ProcessErrorsResponse
    from cogbox_toolbox_api_client_async.models.process_logs_response import ProcessLogsResponse
    from cogbox_toolbox_api_client_async.models.process_restart_response import ProcessRestartResponse
    from cogbox_toolbox_api_client_async.models.process_status import ProcessStatus
    from cogbox_toolbox_api_client_async.models.process_status_response import ProcessStatusResponse
    from cogbox_toolbox_api_client_async.models.pty_create_request import PtyCreateRequest
    from cogbox_toolbox_api_client_async.models.pty_create_response import PtyCreateResponse
    from cogbox_toolbox_api_client_async.models.pty_list_response import PtyListResponse
    from cogbox_toolbox_api_client_async.models.pty_resize_request import PtyResizeRequest
    from cogbox_toolbox_api_client_async.models.pty_session_info import PtySessionInfo
    from cogbox_toolbox_api_client_async.models.recording import Recording
    from cogbox_toolbox_api_client_async.models.replace_request import ReplaceRequest
    from cogbox_toolbox_api_client_async.models.replace_result import ReplaceResult
    from cogbox_toolbox_api_client_async.models.screenshot_response import ScreenshotResponse
    from cogbox_toolbox_api_client_async.models.scroll_response import ScrollResponse
    from cogbox_toolbox_api_client_async.models.search_files_response import SearchFilesResponse
    from cogbox_toolbox_api_client_async.models.session import Session
    from cogbox_toolbox_api_client_async.models.session_command_logs_response import SessionCommandLogsResponse
    from cogbox_toolbox_api_client_async.models.session_execute_request import SessionExecuteRequest
    from cogbox_toolbox_api_client_async.models.session_execute_response import SessionExecuteResponse
    from cogbox_toolbox_api_client_async.models.session_send_input_request import SessionSendInputRequest
    from cogbox_toolbox_api_client_async.models.start_recording_request import StartRecordingRequest
    from cogbox_toolbox_api_client_async.models.status import Status
    from cogbox_toolbox_api_client_async.models.stop_recording_request import StopRecordingRequest
    from cogbox_toolbox_api_client_async.models.user_home_dir_response import UserHomeDirResponse
    from cogbox_toolbox_api_client_async.models.window_info import WindowInfo
    from cogbox_toolbox_api_client_async.models.windows_response import WindowsResponse
    from cogbox_toolbox_api_client_async.models.work_dir_response import WorkDirResponse

_DYNAMIC_IMPORTS: dict[str, str] = {
    "AccessibilityBounds": "cogbox_toolbox_api_client_async.models.accessibility_bounds",
    "AccessibilityInvokeRequest": "cogbox_toolbox_api_client_async.models.accessibility_invoke_request",
    "AccessibilityNodeRequest": "cogbox_toolbox_api_client_async.models.accessibility_node_request",
    "AccessibilityNodesResponse": "cogbox_toolbox_api_client_async.models.accessibility_nodes_response",
    "AccessibilitySetValueRequest": "cogbox_toolbox_api_client_async.models.accessibility_set_value_request",
    "AccessibilityTreeResponse": "cogbox_toolbox_api_client_async.models.accessibility_tree_response",
    "Chart": "cogbox_toolbox_api_client_async.models.chart",
    "ChartElement": "cogbox_toolbox_api_client_async.models.chart_element",
    "CodeRunArtifacts": "cogbox_toolbox_api_client_async.models.code_run_artifacts",
    "CodeRunRequest": "cogbox_toolbox_api_client_async.models.code_run_request",
    "CodeRunResponse": "cogbox_toolbox_api_client_async.models.code_run_response",
    "Command": "cogbox_toolbox_api_client_async.models.command",
    "CompletionContext": "cogbox_toolbox_api_client_async.models.completion_context",
    "CompletionItem": "cogbox_toolbox_api_client_async.models.completion_item",
    "CompletionList": "cogbox_toolbox_api_client_async.models.completion_list",
    "ComputerUseAccessibilityNode": "cogbox_toolbox_api_client_async.models.computer_use_accessibility_node",
    "ComputerUseStartResponse": "cogbox_toolbox_api_client_async.models.computer_use_start_response",
    "ComputerUseStatusResponse": "cogbox_toolbox_api_client_async.models.computer_use_status_response",
    "ComputerUseStopResponse": "cogbox_toolbox_api_client_async.models.computer_use_stop_response",
    "CreateContextRequest": "cogbox_toolbox_api_client_async.models.create_context_request",
    "CreateSessionRequest": "cogbox_toolbox_api_client_async.models.create_session_request",
    "DisplayInfo": "cogbox_toolbox_api_client_async.models.display_info",
    "DisplayInfoResponse": "cogbox_toolbox_api_client_async.models.display_info_response",
    "ExecuteRequest": "cogbox_toolbox_api_client_async.models.execute_request",
    "ExecuteResponse": "cogbox_toolbox_api_client_async.models.execute_response",
    "FileInfo": "cogbox_toolbox_api_client_async.models.file_info",
    "FileStatus": "cogbox_toolbox_api_client_async.models.file_status",
    "FilesDownloadRequest": "cogbox_toolbox_api_client_async.models.files_download_request",
    "FindAccessibilityNodesRequest": "cogbox_toolbox_api_client_async.models.find_accessibility_nodes_request",
    "GitAddRequest": "cogbox_toolbox_api_client_async.models.git_add_request",
    "GitBranchRequest": "cogbox_toolbox_api_client_async.models.git_branch_request",
    "GitCheckoutRequest": "cogbox_toolbox_api_client_async.models.git_checkout_request",
    "GitCloneRequest": "cogbox_toolbox_api_client_async.models.git_clone_request",
    "GitCommitInfo": "cogbox_toolbox_api_client_async.models.git_commit_info",
    "GitCommitRequest": "cogbox_toolbox_api_client_async.models.git_commit_request",
    "GitCommitResponse": "cogbox_toolbox_api_client_async.models.git_commit_response",
    "GitDeleteBranchRequest": "cogbox_toolbox_api_client_async.models.git_delete_branch_request",
    "GitRepoRequest": "cogbox_toolbox_api_client_async.models.git_repo_request",
    "GitStatus": "cogbox_toolbox_api_client_async.models.git_status",
    "InitializeRequest": "cogbox_toolbox_api_client_async.models.initialize_request",
    "InterpreterContext": "cogbox_toolbox_api_client_async.models.interpreter_context",
    "IsPortInUseResponse": "cogbox_toolbox_api_client_async.models.is_port_in_use_response",
    "KeyboardHotkeyRequest": "cogbox_toolbox_api_client_async.models.keyboard_hotkey_request",
    "KeyboardPressRequest": "cogbox_toolbox_api_client_async.models.keyboard_press_request",
    "KeyboardTypeRequest": "cogbox_toolbox_api_client_async.models.keyboard_type_request",
    "ListBranchResponse": "cogbox_toolbox_api_client_async.models.list_branch_response",
    "ListContextsResponse": "cogbox_toolbox_api_client_async.models.list_contexts_response",
    "ListRecordingsResponse": "cogbox_toolbox_api_client_async.models.list_recordings_response",
    "LspCompletionParams": "cogbox_toolbox_api_client_async.models.lsp_completion_params",
    "LspDocumentRequest": "cogbox_toolbox_api_client_async.models.lsp_document_request",
    "LspLocation": "cogbox_toolbox_api_client_async.models.lsp_location",
    "LspPosition": "cogbox_toolbox_api_client_async.models.lsp_position",
    "LspRange": "cogbox_toolbox_api_client_async.models.lsp_range",
    "LspServerRequest": "cogbox_toolbox_api_client_async.models.lsp_server_request",
    "LspSymbol": "cogbox_toolbox_api_client_async.models.lsp_symbol",
    "Match": "cogbox_toolbox_api_client_async.models.match",
    "MouseClickRequest": "cogbox_toolbox_api_client_async.models.mouse_click_request",
    "MouseClickResponse": "cogbox_toolbox_api_client_async.models.mouse_click_response",
    "MouseDragRequest": "cogbox_toolbox_api_client_async.models.mouse_drag_request",
    "MouseDragResponse": "cogbox_toolbox_api_client_async.models.mouse_drag_response",
    "MouseMoveRequest": "cogbox_toolbox_api_client_async.models.mouse_move_request",
    "MousePositionResponse": "cogbox_toolbox_api_client_async.models.mouse_position_response",
    "MouseScrollRequest": "cogbox_toolbox_api_client_async.models.mouse_scroll_request",
    "PortList": "cogbox_toolbox_api_client_async.models.port_list",
    "Position": "cogbox_toolbox_api_client_async.models.position",
    "ProcessErrorsResponse": "cogbox_toolbox_api_client_async.models.process_errors_response",
    "ProcessLogsResponse": "cogbox_toolbox_api_client_async.models.process_logs_response",
    "ProcessRestartResponse": "cogbox_toolbox_api_client_async.models.process_restart_response",
    "ProcessStatus": "cogbox_toolbox_api_client_async.models.process_status",
    "ProcessStatusResponse": "cogbox_toolbox_api_client_async.models.process_status_response",
    "PtyCreateRequest": "cogbox_toolbox_api_client_async.models.pty_create_request",
    "PtyCreateResponse": "cogbox_toolbox_api_client_async.models.pty_create_response",
    "PtyListResponse": "cogbox_toolbox_api_client_async.models.pty_list_response",
    "PtyResizeRequest": "cogbox_toolbox_api_client_async.models.pty_resize_request",
    "PtySessionInfo": "cogbox_toolbox_api_client_async.models.pty_session_info",
    "Recording": "cogbox_toolbox_api_client_async.models.recording",
    "ReplaceRequest": "cogbox_toolbox_api_client_async.models.replace_request",
    "ReplaceResult": "cogbox_toolbox_api_client_async.models.replace_result",
    "ScreenshotResponse": "cogbox_toolbox_api_client_async.models.screenshot_response",
    "ScrollResponse": "cogbox_toolbox_api_client_async.models.scroll_response",
    "SearchFilesResponse": "cogbox_toolbox_api_client_async.models.search_files_response",
    "Session": "cogbox_toolbox_api_client_async.models.session",
    "SessionCommandLogsResponse": "cogbox_toolbox_api_client_async.models.session_command_logs_response",
    "SessionExecuteRequest": "cogbox_toolbox_api_client_async.models.session_execute_request",
    "SessionExecuteResponse": "cogbox_toolbox_api_client_async.models.session_execute_response",
    "SessionSendInputRequest": "cogbox_toolbox_api_client_async.models.session_send_input_request",
    "StartRecordingRequest": "cogbox_toolbox_api_client_async.models.start_recording_request",
    "Status": "cogbox_toolbox_api_client_async.models.status",
    "StopRecordingRequest": "cogbox_toolbox_api_client_async.models.stop_recording_request",
    "UserHomeDirResponse": "cogbox_toolbox_api_client_async.models.user_home_dir_response",
    "WindowInfo": "cogbox_toolbox_api_client_async.models.window_info",
    "WindowsResponse": "cogbox_toolbox_api_client_async.models.windows_response",
    "WorkDirResponse": "cogbox_toolbox_api_client_async.models.work_dir_response",
}


def __getattr__(attr_name: str) -> object:
    module_path = _DYNAMIC_IMPORTS.get(attr_name)
    if module_path is None:
        raise AttributeError(f"module {__name__!r} has no attribute {attr_name!r}")
    mod = importlib.import_module(module_path)
    value = getattr(mod, attr_name)
    globals()[attr_name] = value
    return value


def __dir__() -> list[str]:
    return list(_DYNAMIC_IMPORTS.keys())
