/* tslint:disable */
/* eslint-disable */
/**
 * Cogbox Toolbox API
 * Cogbox Toolbox API. The base URL comes from the sandbox\'s `toolboxProxyUrl` field (returned in sandbox DTO by the main Cogbox API) plus the sandbox ID: `{toolboxProxyUrl}/{sandboxId}/{endpoint}`. Default for Cogbox Cloud: `https://proxy.cogbox.pazity.com/toolbox/{sandboxId}`.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ChartElement {
    'angle'?: number;
    'first_quartile'?: number;
    'group'?: string;
    'label'?: string;
    'max'?: number;
    'median'?: number;
    'min'?: number;
    'outliers'?: Array<number>;
    'png'?: string;
    'points'?: Array<Array<number>>;
    'radius'?: number;
    'third_quartile'?: number;
    'title'?: string;
    'type'?: string;
    'value'?: string;
    'x_label'?: string;
    'y_label'?: string;
}

