=begin
#Cogbox

#Cogbox AI platform API Docs

The version of the OpenAPI document: 1.0
Contact: support@cogbox.com
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

module CogboxApiClient
  VERSION = '0.0.0.pre.dev'
end
